# Generated by Django 4.1.4 on 2023-01-02 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 2, 23, 50, 27, 209738, tzinfo=datetime.timezone.utc)),
        ),
    ]
