# Generated by Django 4.1.4 on 2023-01-03 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 1, 3, 0, 13, 18, 528954, tzinfo=datetime.timezone.utc)),
        ),
    ]
